---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
spec:
  selector:
    matchLabels:
      app: app-api
  replicas: 1
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: candidate-app-api
          image: sujaydevops/candidate-app-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: candidate-service
spec:
  selector:
    app: app-api
  ports:
    - port: 8080
      nodePort: 30001
      protocol: TCP
      targetPort: 8080
  type: NodePort